[package]
name    = "phonenumber"
version = "0.2.0+8.9.0"

authors = ["meh. <meh@1aim.com>"]
license = "Apache-2.0"

description = "Library for parsing, formatting and validating international phone numbers."
repository  = "https://github.com/1aim/rust-phonenumber"
keywords    = ["phonenumber", "phone", "number", "parser", "formatter"]

[dependencies]
regex       = "0.2"
regex-cache = "0.1.5"
lazy_static = "1.0"
fnv         = "1.0"
failure     = "0.1"
quick-xml   = "0.12"
itertools   = "0.7"
either      = "1.0"
nom         = "3.2"

serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.0"

[build-dependencies]
quick-xml    = "0.12"
failure      = "0.1"
regex        = "0.2"
serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.0"
